language: node_js
node_js:
  - node

cache: yarn

script:
  - yarn run lint
  - yarn run compile
  - ./packages/brd/bin/run --version
  - ./packages/brd/bin/run --help
  - yarn run test:ci


after_success:
  - bash <(curl -s https://codecov.io/bash)

